#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_2(
          KC_Q, KC_W, KC_F, KC_P, KC_B,                                 KC_J, KC_L, KC_U, KC_Y, KC_SCLN,

          KC_A, KC_R, MT(MOD_LGUI, KC_S), MT(MOD_LALT, KC_T), KC_G,     KC_M, MT(MOD_RALT, KC_N), MT(MOD_RGUI, KC_E), KC_I, KC_O,

          KC_Z, KC_X, KC_C, KC_D, KC_V,                                 KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH,

                            TO(1), LSFT_T(KC_BSPC),         RCTL_T(KC_SPC), KC_ENT),

    [1] = LAYOUT_split_3x5_2(
          KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC,         KC_AMPR, KC_CIRC, KC_ASTR, KC_TILD, KC_COLN,

          KC_EQL, KC_PLUS, KC_LBRC, KC_LPRN, KC_LCBR,       KC_RCBR, KC_RPRN, KC_RBRC, KC_MINS, KC_UNDS,

          KC_BSLS, KC_PIPE, KC_GRV, KC_QUOT, KC_DQT,        KC_DQT, KC_QUOT, KC_LT, KC_GT, KC_QUES,

                            TO(1), LSFT_T(KC_BSPC),         RCTL_T(KC_SPC), KC_ENT),
};



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

